Feature: Services Administrator

Scenario: Service register
Given I am on the "/services/new"
And I fill in "service_principal_title" with "prueba"
And I fill in "service_principal_subtitle" with "prueba"
And I fill in "service_principal_image" with "prueba"
And I fill in "service_content_principal_title" with "prueba"
And I fill in "service_content_principal_content" with "prueba"
And I fill in "service_content_segundario_title" with "prueba"
And I fill in "service_content_segundario_content" with "prueba"
And I fill in "service_tab_one_title" with "prueba"
And I fill in "service_tab_one_content" with "prueba"
And I fill in "service_tab_one_image" with "prueba"
And I fill in "service_tab_two_title" with "prueba"
And I fill in "service_tab_two_content" with "prueba"
And I fill in "service_tab_two_image" with "prueba"
And I fill in "service_tab_three_title" with "prueba"
And I fill in "service_tab_three_content" with "prueba"
And I fill in "service_tab_three_image" with "prueba"
And I fill in "service_tab_four_title" with "prueba"
And I fill in "service_tab_four_content" with "prueba"
And I fill in "service_tab_four_image" with "prueba"
And I fill in "service_tab_five_title" with "prueba"
And I fill in "service_tab_five_content" with "prueba"
And I fill in "service_tab_five_image" with "prueba"
And I fill in "service_service_title" with "prueba"
And I fill in "service_service_subtitle" with "prueba"
And I fill in "service_service_one_title" with "prueba"
And I fill in "service_service_one_content" with "prueba"
And I fill in "service_service_one_image" with "prueba"
And I fill in "service_service_two_title" with "prueba"
And I fill in "service_service_two_content" with "prueba"
And I fill in "service_service_two_image" with "prueba"
And I fill in "service_service_three_title" with "prueba"
And I fill in "service_service_three_content" with "prueba"
And I fill in "service_service_three_image" with "prueba"
When I press "Guardar"
Then I should see "Registro creado correctamente"

Scenario: editing services
Given existing one register services
When I am on the "/services/1/edit"
And I fill in "service_principal_title" with "edit_prueba"
And I fill in "service_principal_subtitle" with "edit_prueba"
And I fill in "service_principal_image" with "edit_prueba"
And I fill in "service_content_principal_title" with "edit_prueba"
And I fill in "service_content_principal_content" with "edit_prueba"
And I fill in "service_content_segundario_title" with "edit_prueba"
And I fill in "service_content_segundario_content" with "edit_prueba"
And I fill in "service_tab_one_title" with "edit_prueba"
And I fill in "service_tab_one_content" with "edit_prueba"
And I fill in "service_tab_one_image" with "edit_prueba"
And I fill in "service_tab_two_title" with "edit_prueba"
And I fill in "service_tab_two_content" with "edit_prueba"
And I fill in "service_tab_two_image" with "edit_prueba"
And I fill in "service_tab_three_title" with "edit_prueba"
And I fill in "service_tab_three_content" with "edit_prueba"
And I fill in "service_tab_three_image" with "edit_prueba"
And I fill in "service_tab_four_title" with "edit_prueba"
And I fill in "service_tab_four_content" with "edit_prueba"
And I fill in "service_tab_four_image" with "edit_prueba"
And I fill in "service_tab_five_title" with "edit_prueba"
And I fill in "service_tab_five_content" with "edit_prueba"
And I fill in "service_tab_five_image" with "edit_prueba"
And I fill in "service_service_title" with "edit_prueba"
And I fill in "service_service_subtitle" with "edit_prueba"
And I fill in "service_service_one_title" with "edit_prueba"
And I fill in "service_service_one_content" with "edit_prueba"
And I fill in "service_service_one_image" with "edit_prueba"
And I fill in "service_service_two_title" with "edit_prueba"
And I fill in "service_service_two_content" with "edit_prueba"
And I fill in "service_service_two_image" with "edit_prueba"
And I fill in "service_service_three_title" with "edit_prueba"
And I fill in "service_service_three_content" with "edit_prueba"
And I fill in "service_service_three_image" with "edit_prueba"
When I press "Guardar"
Then I should see "Servicio editado correctamente"

Scenario: deleting Service
Given existing one register services
Given I am on the "/services"
When I press deleting
Then I should see "Servicio eliminado correctamente"
